name: pizza_repository
description: "The Repo that handles pizzas"
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # equatable: ^2.0.5
  # firebase_auth: ^4.17.8
  # cloud_firestore: ^4.15.8
  # firebase_storage: ^11.6.9
  # rxdart: ^0.27.7
  # path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true